/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package forward */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 16 "main.go"

#include <stdio.h>
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


//日志模块初始化

extern void InitialLogSetting(GoUint8 p0, GoUintptr p1);

//SpringBoard消息转发

extern void SpringBoardForwardListen();

//SpringBoard客户机限制数量

extern void SetSbsMaxClientConn(GoInt64 p0);

//SpringBoard客户机持久连接间隔

extern void SetSbsClientConnKeepAlive(GoString p0, GoUintptr p1);

//SpringBoard服务监听地址

extern void SetSpringBoardListenAddr(GoString p0);

//转发目标地址

extern void SetSBSLocalTargetAddr(GoString p0);

//SSH服务端连接地址

extern void SetSSHServerAddr(GoString p0);

//SSH服务端监听端口

extern void SetSSHServerListenAddr(GoString p0);

//SSH服务端客户机最大连接数

extern void SetSSHMaxClientConn(GoInt64 p0);

//SSH服务端客户端持久连接间隔

extern void SetSSHClientConnKeepAlive(GoString p0, GoUintptr p1);

//ssh转发目标地址

extern void SetSSHLocalTargetAddr(GoString p0);

extern void SSHTunnelForwardListen();

#ifdef __cplusplus
}
#endif
